# Generated by Django 4.0.5 on 2022-06-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tag_review_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
